package netbeansgui;

import java.awt.Color;
import java.util.Observable;
import java.util.Observer;

/**
 *
 * @author Lucas Wiebe-Dembowski
 */
public class GUI extends javax.swing.JFrame implements userinterface.UserInterface, Observer{
    private class GUIObservable extends Observable{
        public void notify(String msg) {
            setChanged();
            notifyObservers(msg);
        }
    }

    private GUIObservable myObservable = new GUIObservable();
    private String path;

    public GUI() {
        initComponents();
        path = "";
    }
    
    @Override
    public void update(Observable obj, Object arg){ //Observer update() method.
    //NOT TO BE CONFUSED WITH MY UPDATE(STRING) METHOD, DEFINED AT THE BOTTOM OF THIS FILE
        if(arg instanceof String){
            String myText = (String)arg;
            if(myText.contains("Arduino") && myText.substring(0, 7).equals("Arduino")){
                //This message was sent from the arduino, not internally from this program.
                updateArduinoMessages(myText.substring(7, myText.length() - 2)); // -2 to ignore the \r\n at the end
            }else{ //This message was sent internally from this program.
                update(myText);
            }
        }
    }
    
    private void sendMsg(String msg){
         myObservable.notify(msg);
    }
    
    public void addObserver(Observer o){
        myObservable.addObserver(o);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Open = new javax.swing.JButton();
        Close = new javax.swing.JButton();
        quit = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        portName = new javax.swing.JTextField();
        setPortNameButton = new javax.swing.JButton();
        Messages = new java.awt.TextArea();
        stopCode = new javax.swing.JTextField();
        setStopCodeButton = new javax.swing.JButton();
        listPorts = new javax.swing.JButton();
        Stop = new javax.swing.JButton();
        Start = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        PathField = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        leftRoom = new javax.swing.JButton();
        rightRoom = new javax.swing.JButton();
        rightIntersection = new javax.swing.JButton();
        leftIntersection = new javax.swing.JButton();
        sendPath = new javax.swing.JButton();
        clearPath = new javax.swing.JButton();
        ArduinoMessages = new java.awt.TextArea();
        jLabel6 = new javax.swing.JLabel();
        showPath = new javax.swing.JButton();
        numberBox = new javax.swing.JTextField();
        NodeNumberSpinner = new javax.swing.JSpinner();
        nodeNumberButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Open.setText("Open Port");
        Open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenActionPerformed(evt);
            }
        });

        Close.setText("Close Port");
        Close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseActionPerformed(evt);
            }
        });

        quit.setText("Quit");
        quit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitActionPerformed(evt);
            }
        });

        jLabel4.setText("Messages");

        portName.setText("COM6");
        portName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                portNameActionPerformed(evt);
            }
        });

        setPortNameButton.setText("Set Port Name");
        setPortNameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setPortNameButtonActionPerformed(evt);
            }
        });

        stopCode.setText("0x17");
        stopCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopCodeActionPerformed(evt);
            }
        });

        setStopCodeButton.setText("Set Stop Code");
        setStopCodeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setStopCodeButtonActionPerformed(evt);
            }
        });

        listPorts.setText("List Available Serial Ports");
        listPorts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listPortsActionPerformed(evt);
            }
        });

        Stop.setText("Stop");
        Stop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StopActionPerformed(evt);
            }
        });

        Start.setText("Start");
        Start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartActionPerformed(evt);
            }
        });

        PathField.setColumns(20);
        PathField.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        PathField.setRows(5);
        jScrollPane1.setViewportView(PathField);

        jLabel5.setText("Path");

        leftRoom.setText("Left Room ");
        leftRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leftRoomActionPerformed(evt);
            }
        });

        rightRoom.setText("Right Room ");
        rightRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rightRoomActionPerformed(evt);
            }
        });

        rightIntersection.setText("Right Intersection");
        rightIntersection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rightIntersectionActionPerformed(evt);
            }
        });

        leftIntersection.setText("Left Intersecion");
        leftIntersection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leftIntersectionActionPerformed(evt);
            }
        });

        sendPath.setText("Send Path");
        sendPath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendPathActionPerformed(evt);
            }
        });

        clearPath.setText("Clear Path");
        clearPath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearPathActionPerformed(evt);
            }
        });

        jLabel6.setText("Arduino Messages");

        showPath.setText("Show Path");
        showPath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPathActionPerformed(evt);
            }
        });

        numberBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberBoxActionPerformed(evt);
            }
        });

        NodeNumberSpinner.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                NodeNumberSpinnerMouseWheelMoved(evt);
            }
        });

        nodeNumberButton.setText("Node Number");
        nodeNumberButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nodeNumberButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(Open)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Close)
                .addGap(73, 73, 73)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(numberBox, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(153, 153, 153))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(42, 42, 42)
                                        .addComponent(Start)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Stop))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(leftRoom, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(rightRoom, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(leftIntersection, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(rightIntersection, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(sendPath, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(clearPath, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(showPath, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(nodeNumberButton)))
                            .addComponent(quit)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(portName)
                                    .addComponent(stopCode, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(setPortNameButton)
                                    .addComponent(setStopCodeButton))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(listPorts)
                            .addComponent(NodeNumberSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Messages, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ArduinoMessages, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Open)
                            .addComponent(Close)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(numberBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Stop)
                            .addComponent(Start))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(leftRoom)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rightRoom)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(leftIntersection)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rightIntersection)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NodeNumberSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nodeNumberButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sendPath)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(clearPath)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(showPath)
                        .addGap(29, 29, 29)
                        .addComponent(listPorts)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(setPortNameButton)
                                .addGap(4, 4, 4)
                                .addComponent(setStopCodeButton))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(portName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(stopCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(quit))
                    .addComponent(Messages, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(ArduinoMessages, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenActionPerformed
        sendMsg("open");
    }//GEN-LAST:event_OpenActionPerformed

    private void CloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseActionPerformed
        sendMsg("close");
    }//GEN-LAST:event_CloseActionPerformed

    private void quitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitActionPerformed
        sendMsg("q");
    }//GEN-LAST:event_quitActionPerformed

    private void setPortNameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setPortNameButtonActionPerformed
        sendMsg("portName " + portName.getText());
    }//GEN-LAST:event_setPortNameButtonActionPerformed

    private void portNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_portNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_portNameActionPerformed

    private void stopCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stopCodeActionPerformed

    private void setStopCodeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setStopCodeButtonActionPerformed
        sendMsg("stopCode " + stopCode.getText());
    }//GEN-LAST:event_setStopCodeButtonActionPerformed

    private void listPortsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listPortsActionPerformed
        sendMsg("listPorts");
    }//GEN-LAST:event_listPortsActionPerformed

    private void StopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StopActionPerformed
        sendMsg("stop");
    }//GEN-LAST:event_StopActionPerformed

    private void StartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartActionPerformed
        sendMsg("start");
    }//GEN-LAST:event_StartActionPerformed

    private void leftRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leftRoomActionPerformed
        path += "lr_";
        PathField.append("left room ");
        char[] pathArray = path.toCharArray();
//        pathArray[0] = Integer.toString(numNodes);
    }//GEN-LAST:event_leftRoomActionPerformed

    private void rightRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rightRoomActionPerformed
        path += "rr_";
        PathField.append("right room ");
    }//GEN-LAST:event_rightRoomActionPerformed

    private void rightIntersectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rightIntersectionActionPerformed
        path += "ri_";
        PathField.append("right intersection ");
    }//GEN-LAST:event_rightIntersectionActionPerformed

    private void leftIntersectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leftIntersectionActionPerformed
        path += "li_";
        PathField.append("left intersection ");
    }//GEN-LAST:event_leftIntersectionActionPerformed

    private void sendPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendPathActionPerformed
        int x = 0; //Count how many spaces there are. Number of nodes is one more than that.
        for(int i = 0; i < path.length() - 1; i++){ // -1 to avoid counting the sapce at the end.
            if(path.charAt(i) == ' '){
                x++;
            }
        }
        if(x > 0 || !path.isEmpty()) x++;
        sendMsg("path " + Integer.toString(x) + " " + path);
    }//GEN-LAST:event_sendPathActionPerformed

    private void clearPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearPathActionPerformed
        PathField.setText("");
        path = new String("");
    }//GEN-LAST:event_clearPathActionPerformed

    private void showPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPathActionPerformed
        Messages.append(path + "\n");
    }//GEN-LAST:event_showPathActionPerformed

    private void numberBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberBoxActionPerformed
        path += (numberBox.getText() + " ");
        PathField.append(numberBox.getText() + "\n");
    }//GEN-LAST:event_numberBoxActionPerformed

    private void NodeNumberSpinnerMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_NodeNumberSpinnerMouseWheelMoved
        NodeNumberSpinner.setValue((int)NodeNumberSpinner.getValue() - evt.getWheelRotation());
    }//GEN-LAST:event_NodeNumberSpinnerMouseWheelMoved

    private void nodeNumberButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nodeNumberButtonActionPerformed
        path += (Integer.toString((int)NodeNumberSpinner.getValue()) + " ");
        PathField.append(Integer.toString((int)NodeNumberSpinner.getValue()) + "\n");
    }//GEN-LAST:event_nodeNumberButtonActionPerformed

    @Override
    public void update(String theMessage){
        Messages.append(theMessage + "\n");
    }
    
    public void updateArduinoMessages(String theMessage){
        ArduinoMessages.append(theMessage + "\n");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.TextArea ArduinoMessages;
    private javax.swing.JButton Close;
    private java.awt.TextArea Messages;
    private javax.swing.JSpinner NodeNumberSpinner;
    private javax.swing.JButton Open;
    private javax.swing.JTextArea PathField;
    private javax.swing.JButton Start;
    private javax.swing.JButton Stop;
    private javax.swing.JButton clearPath;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton leftIntersection;
    private javax.swing.JButton leftRoom;
    private javax.swing.JButton listPorts;
    private javax.swing.JButton nodeNumberButton;
    private javax.swing.JTextField numberBox;
    private javax.swing.JTextField portName;
    private javax.swing.JButton quit;
    private javax.swing.JButton rightIntersection;
    private javax.swing.JButton rightRoom;
    private javax.swing.JButton sendPath;
    private javax.swing.JButton setPortNameButton;
    private javax.swing.JButton setStopCodeButton;
    private javax.swing.JButton showPath;
    private javax.swing.JTextField stopCode;
    // End of variables declaration//GEN-END:variables
}
